### ISSUE TITLE
Feedback Checklist #1

### ISSUE THREAD

**Issue by Jongwoo-Han** [Jongwoo-Han/Class_Registration_System#1]
* [] JSP MVC 패턴 적용
* [] 강좌 다중 선택 구현(배열 넘기기, 신청 & 삭제)
* [] Table 디자인 변경(담기, 신청, 삭제 링크 하나하나 대신 하나의 버튼으로 관리)
