### ISSUE TITLE
Feedback Checklist

### ISSUE THREAD

**Issue by Jongwoo-Han** [Jongwoo-Han/Class_Registration_System#2]
- [x] 로그인(세션 생성)
- [x] 로그아웃(세션 제거)
- [x] 책가방으로 이동
- [x] 강좌 찾기
- [x] 강좌 책가방에 담기(여러 개)
- [x] 강좌 찾기 페이지에서 강좌 신청하기(여러 개)
- [x] 책가방에서 강좌 신청하기(여러 개)
- [x] 강좌 삭제하기(담기 & 신청)
